#!/bin/busybox sh

## LOAD HELPER FUNCTIONS (modify helper-functions.sh as necessary)
source import.sh
clear

## MAIN INIT SEQUENCE
print "Starting boot sequence"
# Mount /sys,/dev,/proc
mount_tmp

# Mount rootfs (unencrypted)
mount_root

## SETUP FS crypto
# Start tcsd (TPM)
tcsd_init

# Debug shell
#rescue_shell

# Decrypt keyfile using tpm_unseal (input password) 
decrypt key.enc /key
encrypted_mount /key /mnt/root/home encrypted
shred /key

# Shutdown tcsd and cleanup
tcsd_exit

# Cleanup /sys, /dev, /proc
umount_tmp

## EXECUTE INIT
#openrc
systemd
